theme = "hyde-y"
baseurl = "http://statistikwerkstatt.org"
languageCode = "de-DE"
title = "StatistikWerkstatt Leipzig"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
metaDataFormat = "yaml"
paginate = 5
paginatePath = "page"
relativeurls = true

copyright = "(c) Nikolai Huckle"

[author]
    name = "George Black"
    email = "statistikwerkstatt@posteo.de"
    
[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    #brand = "Statistik Werkstatt Leipzig"#"<i class='fa fa-heart'></i> & statistics"
    brand = "![](/sw_logo_text_small.png)"
    topline = "Georg-Schwarz-Straße 138 <br> 04179 Leipzig"
    footline = "Created with [Hugo](http://gohugo.io), the [Hyde-Y](https://github.com/enten/hyde-y) theme and [blogdown](https://github.com/rstudio/blogdown)<br>Hosted on an eco-friendly server by [manitu](https://www.manitu.de/)<br>[Imprint](http://www.statistikwerkstatt.org/imprint)"

    # Used when a given page doesn't set its own.
    defaultDescription = "Your default page description"
    defaultKeywords = "your,default,page,keywords"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "start"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    #github = "georgeblck" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "statistikwerkstatt.org" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    instagram = "green_leutzsch"
    posts_navigation = true
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []