# die StatistikWerkstatt
#### Anlaufstelle für statistische Fragen & Probleme

___
___

## Beratung für wissenschaftliche Arbeiten

Verzweifelst du gerade an dem Datensatz deiner Bachelor-, Master- oder Doktorarbeit?
Egal ob SPSS, Stata oder R, egal welches Fach, solange quantitative Methoden verwendet werden, helfe ich dir gerne bei der Ausarbeitung deiner Datenanalyse.

Schick mir dazu am besten eine Mail in der du mir die wichtigsten Informationen deiner Arbeit erklärst (Studiengang, Software, Daten, Abgabetermin).

## Statistik-Nachhilfe

Benötigst du (und deine Freunde) Hilfe für die Vorbereitung einer Prüfung im Bereich Statistik, das Lösen von Übungsblättern während des Semesters oder andere konkrete Unterstützung gebe ich dir gerne Nachhilfe.

Schicke mir dazu die Unterlagen deiner Vorlesung und erkläre kurz inwieweit du Hilfe brauchst und wann die Prüfung ist.

___
___


## Für Leipziger und Nicht-Leipziger

Falls du in Leipzig wohnst findet der Unterricht in meinen Räumlichkeiten in Leipzig-Leutzsch statt. **Eine vorherige Terminabsprache ist immer nötig**, also schreib mir eine Mail bevor Du kommst.

Ansonsten findet der Unterricht online über Skype statt.

```{r leutzsch-map, echo=FALSE}
library(leaflet)

statIcon <- makeIcon(
  iconUrl = "sw_logo.svg",
  iconWidth = 38, iconHeight = 75,
  iconAnchorX = 0, iconAnchorY = 0
)

m <- leaflet(width = "100%", height = "500px", padding = 2) %>%
  setView(lat = 51.347738, lng = 12.314049, zoom = 15) %>%
   #setView(lat = 51.337356, lng = 12.346936, zoom = 13) %>%
  addMarkers(lng=12.314049, lat=51.347738, icon = statIcon) %>%
  addProviderTiles(providers$Stamen.Watercolor,  options = providerTileOptions(opacity = 0.60))%>%
  addProviderTiles(providers$Hydda.RoadsAndLabels)

m
```
