---
title: []
author: NH
date: '2018-01-17'
categories: []
tags: []
---

# Wieso
___

Während meines Studiums habe ich sowohl als Tutor Statistikkurse & Nachhilfe angeboten als auch im erweiterten Freundeskreis bei einigen empirischen Bachelor- und Masterarbeiten mitgeholfen.

Die Vermittlung von Statistik hat mir so viel Freude bereitet, dass ich mir vornahm in Leipzig einen außeruniversitären, zwanglosen Raum anzubieten in dem gemeinsam mit Statistik gearbeitet werden kann - die StatistikWerkstatt ist das Resultat dieses Wunsches.
Nachdem ich nun dutzende Abschlussarbeiten betreut und in verschiedensten Fächern Nachhilfe gegeben kann ich sagen, dass es mir immer noch sehr sehr viel Spaß macht.

Also melde dich gerne und komm vorbei.


# Kosten
___
Eine erste Beratung zu deinen Problemen ist **immer** kostenfrei. Wenn du mehr als einen groben Fahrplan für deine Arbeit/dein Projekt benötigst sind die Stundenpreise (à 60 Minuten) wie folgt:

* Haus- oder Bachelorarbeit: 20€
* Master- oder Doktorarbeit: 25€

Der Preis für Nachhilfestunden hängt sowohl vom Schwierigkeitsgrad als auch der Gruppengröße ab und wird deswegen einzeln ausgehandelt.
