---
title: []
author: NH
date: '2018-03-01'
categories: []
tags: []
---

# Für Firas :)




```{r include=FALSE, cache=FALSE}
library(plyr); library(dplyr)
library(pastecs)
library("PerformanceAnalytics")
library(Hmisc)
library(corrplot)
library(mosaic)
```

## Die Deskriptiven Statistiken

```{r descr, echo = FALSE , out.width = '\\maxwidth'}
total.annual <- read.csv2("totalannual.csv")

options(scipen = 100)
options(digits = 2)

## Deskriptive Statistiken
descr.data <- as.data.frame(total.annual[, c("AmihudMean", "AmihudV2Mean", "BidAskMean", 
    "CSR", "Asset4CSR", "LogTotalAssets", "LogMarktkapitalisierung", 
    "Turnover", "ReturnVolatility", "DebtRatio", "MTB", "Aktienrendite", "logAktienkurs")])
descr.data$AmihudMean <- descr.data$AmihudMean * 10^6
descr.data$AmihudV2Mean <- descr.data$AmihudMean * 10^6
stat.desc(descr.data)

```

## Korrelationen als Grafik und Matrix 

```{r corr, echo = FALSE ,out.width = '\\maxwidth'}
## Korrelationsmatrix
cor_5 <- rcorr(as.matrix(descr.data), type = "pearson")
M <- cor_5$r
p_mat <- cor_5$P

# Als Grafik
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", 
    "#4477AA"))
corrplot(M, method = "color", col = col(200), type = "upper", 
    #order = "hclust", 
    addCoef.col = "black", tl.col = "darkblue", 
    tl.srt = 45, p.mat = p_mat, sig.level = 0.05, diag = TRUE)
# Als Tabelle
cat("The Correlations:\n")
print(cor_5$r)
cat("The p-Values:\n")
print(cor_5$P)
cat("The pairwise number of observations:\n")
print(cor_5$n)
```

## Die Verteilung von CSR

```{r CSR, echo = FALSE ,out.width = '\\maxwidth'}
############################## CSR-Variable 1. Nur die Verteilung von CSR
cat("The Statistics of CSR:\n")
print(favstats(total.annual$CSR))
ggplot(total.annual, aes(x = CSR)) + geom_histogram(binwidth = 1, 
    colour = "black", fill = "white", na.rm = TRUE) + ylim(0, 100) + xlim(0, 
    40) + ylab("Häufigkeit")+ggtitle("Histogram of CSR-Values")

# 2. CSR vs Asset4CSR
ggplot(total.annual, aes(x = CSR, y = Asset4CSR)) + geom_point(na.rm = TRUE) + 
    geom_smooth(method = "lm",na.rm = TRUE)+ggtitle("CSR vs. Asset4CSR")

```

## Die Verteilung der IV-Variable

```{r iv, echo = FALSE ,out.width = '\\maxwidth'}

############################## Die IV-Variable
cat("Tabelle der LegalCodeOrigin-Häufigkeiten")
print(table(total.annual$LegalOrigin))
ggplot(total.annual, aes(x = LegalOrigin)) + geom_bar(stat = "count", 
    width = 0.7, fill = "steelblue", na.rm = TRUE) + ylab("Häufigkeit") + 
    xlab("Legal Origin") + ylim(0, 1000)+ggtitle("Häufigkeiten der LegalCodes")

```

## Die Verteilung von CSR per LegalCode 

```{r csr_iv, echo = FALSE ,out.width = '\\maxwidth'}

################# Die Verteilung von CSR pro LegalOrigin
cat("Deskriptive Statistiken der CSR-Variable pro LegalCode:\n")
print(favstats(CSR ~ LegalOrigin, data = total.annual))
mu <- ddply(total.annual, "LegalOrigin", summarise, grp.mean = mean(CSR, 
    na.rm = TRUE))
# Histogram
ggplot(total.annual, aes(x = CSR, ..density..)) + geom_histogram(color = "black", 
    fill = "white", binwidth = 2, na.rm = TRUE) + facet_grid(LegalOrigin ~ 
    .) + geom_vline(data = mu, aes(xintercept = grp.mean, color = "red"), 
    linetype = "dashed") + ylab("Relative Häufigkeit") + theme(legend.position = "none")+
  ggtitle("Relative Häufigkeit der CSR-Variable pro LegalCode\nRoter Strich = Mittelwerte")
# Als Boxplot
ggplot(total.annual, aes(y = CSR, x = LegalOrigin)) + geom_boxplot(na.rm = TRUE) + 
    ylim(0, 40) + geom_jitter(alpha = 0.1,na.rm = TRUE) + xlab("Legal Origin")+
  ggtitle("Boxplots der CSR-Variable pro LegalCode")

```

